version: "3.8"

services:
  just_chat:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./src/:/just_chat/src:ro
      - ./alembic:/just_chat/alembic
    ports:
      - "8000:8000"

#    depends_on:
#      postgres:
#        condition: service_healthy

#  postgres:
#    image: postgres:latest
#    environment:
#      POSTGRES_USER: "postgres"
#      POSTGRES_PASSWORD: "postgres"
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
#      interval: 1s
#      timeout: 1s
#      retries: 30

