version: "3.8"

services:
  just_chat_tests:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./src/:/just_chat/src:ro
      - ./alembic:/just_chat/alembic
      - ./tests:/just_chat/tests
    environment:
      - POSTGRES_URI=postgresql://postgres:postgres@postgres:5432/postgres
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: bash -c "alembic upgrade head && pytest -vvv"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 1s
      timeout: 1s
      retries: 5

